### ISSUE TITLE
Investigate Online Town for scheduled breaks

### ISSUE THREAD

**Issue by emdupre** [nilearn/Nilearn-Montreal-2020#10]
@GaelVaroquaux suggested we could use [Online Town](http://town.siempre.io) to host our scheduled breaks, much as they're doing at this year's ICLR with [ICLR town](https://twitter.com/mstanojevic118/status/1255474837105106945?s=20).

It would be nice to try this out and see how we could structure it to encourage interaction !

**Comment by PeerHerholz** [comment]
@emdupre could you maybe update the `Online Town` link? I'm getting a 404.

**Comment by emdupre** [comment]
Sorry, @PeerHerholz: I hadn't included the `http` in front of the link. Try it now.

**Comment by PeerHerholz** [comment]
works, thx!

**Comment by emdupre** [comment]
For an unrelated event, we contacted the creators of online town and it sounds like this openly available version is only guaranteed to provide a lag-free experience for <=50 attendees. If we want to guarantee more than that we'd likely need to work with them directly. See: https://gather.town/

**Comment by bthirion** [comment]
Are we likely going to have more than 50 people during the breaks ? I doubt it. 
Best, 
B 

De: "Devon Hjelm" <notifications@github.com>

**Comment by bthirion** [comment]
So far, we have nothing for the breaks.  can somebody set up the  Online Town thing ?
Best

**Comment by emdupre** [comment]
@GaelVaroquaux created one at: https://town.siempre.io/ocZ5ZFmJS6cUNKWx/nilearn

**Comment by bthirion** [comment]
OK, then I add it to the event agenda.

**Comment by emdupre** [comment]
Closing as we used it for the Software days, and it worked well ! :smile_cat:
