### ISSUE TITLE
Decide where to host recordings of talks

### ISSUE THREAD

**Issue by emdupre** [nilearn/Nilearn-Montreal-2020#12]
We've discussed recording the talks and posting them online so that they're easily accessible after the event. We should agree on the exact platforms to post the recordings (keeping in mind that the exact platform decided in #6 may have different integrations available).

The most obvious English-language streaming site is Youtube. @Vincent-wq had suggested Bilibili as a Chinese-language streaming site that we could also upload recordings on. 

Any feedback on these platforms, or other suggestions ?

**Comment by bthirion** [comment]
Youtube is the simplest solution I think.

**Comment by GaelVaroquaux** [comment]
+1 for Youtube.

Vincent, can you confirm that you'll rehost on a chinese platform.

Once this is decided, we should indicate it on the website.

**Comment by emdupre** [comment]
OK, it seems that CrowdCast will maintain its own recording, and our livestream should persist on youtube after the fact.

I think our priority now would be generating CrowdCast event links to update the website with.

**Comment by bthirion** [comment]
But we should link to the Youtube account ? I couldn't do that because I don't have the nilearn dev ids to log on to Youtube.

**Comment by emdupre** [comment]
> I couldn't do that because I don't have the nilearn dev ids to log on to Youtube.

I added the info (for that account and for the stream set up) in our shared email :smile_cat: 

Ideally we'd like both the youtube and the crowdcast links for each lecture. I think we need the events created to grab those, though !

**Comment by emdupre** [comment]
I'm going to close this since @bthirion generated all of the relevant links (thanks again !). After all of the talks are recorded we can think about redistributing them.
