### ISSUE TITLE
Categorize Nilearn issues for the sprint

### ISSUE THREAD

**Issue by emdupre** [nilearn/Nilearn-Montreal-2020#13]
@thomasbazeille has done a great job of going through the [Nilearn issue tracker](https://github.com/nilearn/nilearn/issues) to identify stale or duplicate issues.

It would be great to do another pass specifically to add the [`Good first issue` label](https://github.com/nilearn/nilearn/issues?q=is%3Aopen+is%3Aissue+label%3A%22Good+first+issue%22), so that we can quickly point contributors there during the sprint. Also, if we could generally label the issues (with e.g., `Documentation`, `Maintenance`) I think that would help folks to more quickly filter according to their interests !

**Comment by thomasbazeille** [comment]
I think besides that, we may also need to define some priorities. This was the point of my going through the issues. I guess we could set up a github project for that ? But since I didn't see yet @emdupre on GH for project management I'm not sure what it should look like

 Here is an incomplete and subjective first list.  

-  areas of recurring issues such as Decoder docs and bugs(#2414, #2415, #2360, #2211, #2200), Maskers
- bugs that still await fixing (including documentations) #2358, #1755, #629, #1890, #1736, #1241, #1889,  #72, 2281, #2395, #2354, #2328, #2293, #2393, #2409
- new features that are popular or easy :#2421, #2407, #2385, #2366, #2412, #104
- stalled features and PR that we should push through #1890, #2143, #1730 and many more
- things that need heavy review : #2423, #2425

**Comment by jeromedockes** [comment]
#2224 has been merged already, no?

**Comment by emdupre** [comment]
Thanks for the listing, @thomasbazeille ! Do you think we should make a "sprint" project board and add these there ? I'd use the following issue labels (in the order you've listed the issues):

- Important
- Bug
- New feature
- Need review (I'd really prefer the "stalled" label, here, but we don't have it right now. Do you think we should make it ?)
- Need review

**Comment by kchawla-pi** [comment]
Instead of stalked or needs review, we should make a label Looking for new
contributor . It's a more encouraging one for people.

**Comment by emdupre** [comment]
I don't think something that needs heavy review is appropriate for a new contributor.

I'd love to add "Good first issue" label on some subset of these, but I think those should be identified on a case-by-case basis ! It'd be great if someone could do another sweep for that :smile_cat:

**Comment by kchawla-pi** [comment]
Ok. Stalled can be intimidating even for experienced devs. It implies
there's something that needs serious untangling to be made workable.

Something that implies carrying the baton sentiment would be nicer.

**Comment by emdupre** [comment]
> Something that implies carrying the baton sentiment would be nicer.

Some of the "stalled" issues still have active Nilearn contributors; I'm not sure if they're ready to hand-off or not. Maybe it's worth pinging in on those issues, generally ?

**Comment by kchawla-pi** [comment]
My suggestion was not a blanket one. If the original authors are interested
in following up then great. My idea was to not use words that may intimate
new contributors.

**Comment by jeromedockes** [comment]
Hi, thanks a lot for making this list. we should put it somewhere on the
repo it is super useful.


>  Here is an incomplete and subjective first list.  
>
> -  areas of recurring issues such as Decoder docs and bugs(#2414, #2415, #2360, #2211, #2200), Maskers

I think for 2414, 2415, (maybe) 2360 what needs to be done is clear for
you Binh and I and having someone else look into it would be
inefficient. I think 2211 and 2200 are low priority atm.

> - bugs that still await fixing (including documentations) #2358, #1755, #629, #1890, #1736, #1241, #1889,  #72, 2281, #2395, #2354, #2328, #2293, #2393, #2409

I think that this is where contributions would be most useful

> - new features that are popular or easy :#2421, #2407, #2385, #2366, #2412, #104

Some participants might like to work on these

> - stalled features and PR that we should push through #1890, #2143
> - things that need heavy review : #2224,#2423, #2425

2224 has been merged, did you mean something else? the other too indeed
need much discussion

**Comment by thomasbazeille** [comment]
> Thanks for the listing, @thomasbazeille ! Do you think we should make a "sprint" project board and add these there ?

Yes I'm willing to start it, is "Basic Kanban" style ok with you @emdupre ?

> I'd love to add "Good first issue" label on some subset of these, but I think those should be identified on a case-by-case basis ! It'd be great if someone could do another sweep for that

Ok will put issues there with appropriate labels and everyone can complete what's missing.

Also I think we should maybe schedule some remote discussion timings for important matters on which we want to put everyone on the same page. (e.g. Surface support extent, maybe other things?) Wdyt?

 <del>   One example timing could be Wed 20th at 4p.m CET. </del>

**Comment by jeromedockes** [comment]
> Also I think we should maybe schedule some remote discussion timings for important matters on which we want to put everyone on the same page. (e.g. Surface support extent, maybe other things?) Wdyt?

yes I think that's a good idea

Jérôme.

**Comment by emdupre** [comment]
This all sounds great ! 

My light request is if we could push the surface support meeting by 30mins <del> to 4:30p  </del>CET so I could make it :sweat_smile: 

But I'm :100: on scheduling the meetings and making the board, thank you @thomasbazeille !!

**Comment by thomasbazeille** [comment]
Hello the github project is there : https://github.com/nilearn/nilearn/projects/5
I think of it as a good tool for :
- interested people to find useful work to do on nilearn (Bug, Enhancement sections) 
- for us to recapitulate reviewing task/ act on stalled PRs
- to monitor was is launched / done during the sprint

Please review it, add important stuff that could be missing. 

Also are there some topics where we want many people at once (to survey community interests ? Or shape the future direction in some particular area ?) If so, we should schedule a call and inform key people as much as possible.

There is already the meeting to discuss Surface support on Wednesday at 18:00 CET / 11:00 EDT
