### ISSUE TITLE
Decide on sprint infrastructure

### ISSUE THREAD

**Issue by emdupre** [nilearn/Nilearn-Montreal-2020#14]
There's still a bit of infrastructure that remains undecided for the sprint. In particular:

1. **Hub locations:** Since this is a global sprint, we'll likely need several key "hubs" to coordinate nearby time zones. Paris and Montreal are logical hubs for Europe and the Americas. Do we have any other locations with at least one long-term Nilearn contributor that could act as a hub ?
1. **Sprint hosts**: For each of the hubs, ideally we would have several "hosts" online throughout the sprint. Hosts could help to troubleshoot contributor issues and keep development moving forward. We should likely pool from our organizing team, here, but this could be anyone with a good understanding of the Nilearn code base ! It'd be great to have several folks identified so that hosts could work in shifts within a given hub.
1. **Chat rooms**: It'd be great to have a chat room where contributors could ask questions during the sprint and to keep a social aspect to the event. We should decide on a platform to host the chat.

**Comment by bthirion** [comment]
1. Regarding hubs, I don't think we can do more than Paris + Montreal.
2. We can have a few additional hosts. it' s time to contact them indeed. 
3. Yes. Mattermost ?

**Comment by thomasbazeille** [comment]
I like the idea of having an audio room as well were the current host are connected and can answer questions live or discuss with people that are willing to.

Don't know which platform makes that easy besides discord but not sure it's very professional.

**Comment by emdupre** [comment]
Discussions will be important, particularly for https://github.com/nilearn/nilearn/pull/2435#issuecomment-627922009 !

Happy to try Discord (I've never used it, but I've heard good things !) or we could schedule a video call. Even if we use Discord I'd prefer that we schedule a set time for some of these discussions !

**Comment by bthirion** [comment]
No experiment with Discord, but can try.

**Comment by emdupre** [comment]
@thomasbazeille do you have a Discord room (server ?) that we can direct people to join ?

**Comment by thomasbazeille** [comment]
Here is the link of a dedicated discord room : https://discord.gg/bMBhb7w

**Comment by emdupre** [comment]
Closing as this has been finalized. Thanks for setting it up, @thomasbazeille !!
