### ISSUE TITLE
Confirm that Nilearn CI is ready for sprint

### ISSUE THREAD

**Issue by emdupre** [nilearn/Nilearn-Montreal-2020#15]
@jeromedockes has been working on the continuous integration and coverage reports for Nilearn (see https://github.com/nilearn/nilearn/pull/2419) to ensure that they're ready for the sprint. This issue is just to keep track of any other improvements we'd like to make, there !

**Comment by emdupre** [comment]
Should we just merge https://github.com/nilearn/nilearn/pull/2434, @jeromedockes ? Is there anything else you'd like to wrap up, here ?

**Comment by jeromedockes** [comment]
> Should we just merge https://github.com/nilearn/nilearn/pull/2434,
> @jeromedockes ?

I think so

> Is there anything else you'd like to wrap up, here ?

Not sure, what do you have in mind?
One thing that we have discussed that is related to CI is mocking
fetchers but this definitely won't be addressed before the sprint

@kchawla-ci do you think we need to ask ci providers for more resources
during the sprint, I think you have done that in the past?

**Comment by emdupre** [comment]
@kchawla-pi did you ask for more resources from CI providers during the last Nilearn sprint ? If so, what was the turnaround on being granted those ?

**Comment by kchawla-pi** [comment]
Asking for more resources was very expensive.
I would direct contributors to create the environment so they can run the Doc builds locally, and to do so before any PR are merged.
Last sprint was smaller so I was running everyone's PR's docs on my machine and making fixes. 
The two approaches outlines above together should be sufficient.

Pace the merges, so each PR is merged only after CircleCI has greened on it. That's my suggestion.

**Comment by kchawla-pi** [comment]
It was expensive in terms of money last time but also time. ultimate;y we were not really getting too much out of it that we couldn't handle locally using the approach outlined above.

If any doc building problems leak through, they can be fixed after the sprint.

It might be different this time around but I cannot speculate on that.

**Comment by jeromedockes** [comment]
> Asking for more resources was very expensive.

good to know!
