### ISSUE TITLE
Sylvia Villeneuve's webstie expired.

### ISSUE THREAD

**Issue by kchawla-pi** [nilearn/Nilearn-Montreal-2020#23]
Her website expired on May 10th it seems. We should add a different link on the Dev Days page.

**Comment by emdupre** [comment]
Thanks for catching this !

Want to update the link to point here, @kchawla-pi ? https://douglas.research.mcgill.ca/fr/sylvia-villeneuve

**Comment by emdupre** [comment]
We should notify her, as well. Maybe in the follow-up where we suggest times to test Crowdcast.

**Comment by emdupre** [comment]
Closed with https://github.com/nilearn/dev-days-2020/commit/120877775ffc02fcbd018b0b5510c7231091545b
