### ISSUE TITLE
Update timing on software day

### ISSUE THREAD

**Issue by emdupre** [nilearn/Nilearn-Montreal-2020#5]
@GaelVaroquaux, you're currently scheduled to give a half-hour intro to the software development day. Based on conversations in #4, it sounds like folks are generally concerned about avoiding long intros. 

Do you want to drop it to 15 mins and shift the schedule up, Gaël ? We could re-contact all speakers at once with both days's schedules.

**Comment by GaelVaroquaux** [comment]
> Do you want to drop it to 15 mins and shift the schedule up, Gaël ?

Sounds good!

**Comment by thomasbazeille** [comment]
If it's just that I pushed a fix in #4, used the additional time to increase a bit the lunch break.

**Comment by emdupre** [comment]
Closed with #4 !
