### ISSUE TITLE
Contact speakers with schedule, platform

### ISSUE THREAD

**Issue by emdupre** [nilearn/Nilearn-Montreal-2020#7]
We should re-contact our speakers with ~(1) the newest schedule and (2)~ our finalized platform.

This will serve to confirm their availability and communicate how we expect their handle their presentations; for example, will every speaker be able to share their screen ? Should we test connections beforehand ?

EDIT: @GaelVaroquaux contacted speakers with the current schedule on 30 April !

**Comment by GaelVaroquaux** [comment]
I think that I should close this one: I contacted. I'll follow up with them.
