### ISSUE TITLE
Finalize website theme

### ISSUE THREAD

**Issue by emdupre** [nilearn/Nilearn-Montreal-2020#8]
@GaelVaroquaux was kind enough to create the current website; I misunderstood its framework and so created a fork at: https://emdupre.github.io/bulma-clean-theme. 

It might be worth either updating the current theme such that individual events are better delineated on separate pages _or_ porting over the Bulma Clean theme. This should help in advertising -- and archiving, as recordings are uploaded -- individual events !

**Comment by bthirion** [comment]
Sounds right.

**Comment by GaelVaroquaux** [comment]
Just to make sure that I understand things right: you would like to
separate a few pages out, right, as on the version on your github?

**Comment by GaelVaroquaux** [comment]
> you would like to separate a few pages out, right, as on the version on your github?

I've pushed to the website the corresponding refactoring:
https://nilearn.github.io/dev-days-2020

I hope that this is what you had in mind.

If it's fine, I'll let you close the issue.

**Comment by bthirion** [comment]
LGTM !

**Comment by jeromedockes** [comment]
Links to the schedules are broken, I can open a PR

**Comment by GaelVaroquaux** [comment]
> Links to the schedules are broken,

Thanks for spotting this.

> I can open a PR

Or push to master

**Comment by emdupre** [comment]
Great, thank you !
