### ISSUE TITLE
Create list of places to advertise

### ISSUE THREAD

**Issue by emdupre** [nilearn/Nilearn-Montreal-2020#9]
After we re-confirm with speakers (see #7 ) we should do a bigger advertising push of the finalized website (potentially, also see #8). It'd be nice to collect a list of places beforehand such that we can get this out quickly. Here's an initial list; please add as many other resources as you can think of !

- [x] NITRC calendar (done by @kchawla-pi on 29/4)
- [x] Pinned Nilearn GitHub issue
- [x] Twitter with the #nilearn hashtag
- [x] NeuroStars
- [x] NiPy mailing list
- [x] BIC mailing list (internal to the MNI)

**Comment by bthirion** [comment]
No better suggestion !

**Comment by PeerHerholz** [comment]
Not sure how feasible the following are...furthermore the overlap with the already listed resources might be quite big, just brainstorming:

- [ ] BIDS mailing list 
- [ ] ReproNim mailing list 
- [ ] MILA/UNIQUE
- [ ] nilearn website
- [x] brainhack slack/mattermost

If someone is feeling rowdy (hehe): SPM/FSL/AFNI/FreeSurfer mailing list.

**Comment by bthirion** [comment]
+ HCP mailing list ;-)

Can do Nipy ML, Neurostars, HCP.

**Comment by GaelVaroquaux** [comment]
- [x] FSL Mailing list
- [x] SPM Mailing list
- [x] Neurospin Mailing list

I'll do these as soon as we have confirmation from the speakers.

**Comment by GaelVaroquaux** [comment]
https://www.worldwideneuro.com/ => done

**Comment by GaelVaroquaux** [comment]
I've advertised as much as I could and updated the list above. Please send announcements where I could not.

**Comment by thomasbazeille** [comment]
Do we have a mean to contact nistats past contributors as well ?

**Comment by bthirion** [comment]
I've done mine.
Best,
B

**Comment by emdupre** [comment]
Closing, but please keep advertising !

**Comment by kchawla-pi** [comment]
We can contact nistats past contributors via GitHub

**Comment by thomasbazeille** [comment]
Reopening just to ping everyone, can you advertise again in places you did the first time if it feels right ?

It would be great to communicate on the results of this up-to-now and the last day of conference. The best would be to link replays of the Software day talks as well but i'm not sure these are ready.
I already posted the message below on :

- [x] Neurostars
- [x] Github issue

--

Thanks a lot to the 100+ people that participated in the Software Day and the 40 sprinters, felt that we made some big steps forward and improved quite a lot of things in only two days.

While we clean and merge all of that : see you today at the Scientific Day(https://nilearn.github.io/dev-days-2020/scientific_days.html) conferences about how using nilearn and other softwares makes great research happen.

**Comment by kchawla-pi** [comment]
Twitter is a good place to quickly reach people. If the sprinters and us tweet about this and tag it right, we can get the word out far and wide.

Condensed Thomas' spiel  for Twitter

-----
100+ audience for Software Day & 40 coders for Code Sprint! We made some big steps forward & improved quite a lot of things in only two days.
See you today at Scientific Day(https://nilearn.github.io/dev-days-2020/scientific_days.html) conferences about how using #nilearn & other softwares enables great research!!

**Comment by bthirion** [comment]
+FSL +nipy-devel
